version: 2 
jobs: 
  build:
    working_directory: ~/bitbucket-pipelines-cli

    docker: 
      - image: circleci/openjdk:8-jdk-browsers 

    steps: 

      - checkout 

      - restore_cache: 
          key: bitbucket-pipelines-cli-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache: 
          paths:
            - ~/.m2
          key: bitbucket-pipelines-cli-{{ checksum "pom.xml" }}

      - run: mvn package && mv target/bitbucket-pipelines-cli-jar-with-dependencies.jar target/bitbucket-pipelines-cli.jar

      - store_test_results: 
          path: bitbucket-pipelines-cli/target/surefire-reports

      - store_artifacts:
          path: bitbucket-pipelines-cli/target/jacoco-reports

      - store_artifacts:
          path: bitbucket-pipelines-cli/target/bitbucket-pipelines-cli.jar