version: 2 
jobs: 
  build:
    working_directory: ~/bitbucket-pipelines-cli

    docker: 
      - image: circleci/openjdk:8-jdk-browsers 

    steps: 

      - checkout 

      - restore_cache: 
          key: bitbucket-pipelines-cli-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline
      - run: mvn package -DskipTests

      - save_cache: 
          paths:
            - ~/.m2
          key: bitbucket-pipelines-cli-{{ checksum "pom.xml" }}

      - run: mvn package && mv target/bitbucket-pipelines-cli-jar-with-dependencies.jar target/bitbucket-pipelines-cli.jar

      - run:
          name: Generate SHA from the jar file
          command: ./createShaFromJar.sh target/bitbucket-pipelines-cli.jar

      - store_test_results: 
          path: target/surefire-reports

      - store_artifacts:
          path: target/jacoco-reports

      - store_artifacts:
          path: target/bitbucket-pipelines-cli.jar

      - store_artifacts:
          path: target/bitbucket-pipelines-cli.jar.sha256sum.txt

      - run:
          name: Release artifact into GitHub Releases
          command: ./release-to-github.sh target/bitbucket-pipelines-cli.jar